rule:
  number_of_decks: 8
  cut_card_proportion: 0.3333333
  split_all_limits: 1
  split_ace_limits: 1
  double_policy: AnyTwo
  dealer_hit_on_soft17: true
  allow_das: true
  allow_late_surrender: true
  peek_policy: UpAceOrTen

  payout_blackjack: 1.5
  payout_insurance: 0.0

blackjack_simulator:
